# Header
menu:
  主页: /
  所有文章: /archives
  简历: http://resume.zanyuyu.com

# SubNav
subnav:
  github: "https://github.com/zanseven007"
  weibo: "http://www.weibo.com/zanyuyu"
  # rss: "#"
  zhihu: "https://www.zhihu.com/people/zan-yu-yu-35"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 
language: zh-Hans
# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/cool.jpg
#是否开启分享
share_jia: false
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
changyan: true
changyan_appid: cysYEyE1q
changyan_appkey: 70c5ff76a5bcbd033799e79cd9520be3
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  anotherhome: https://www.anotherhome.net/
  暮光博客: http://muguang.me/
  大撸子の狗窝: http://shawblog.me/
  张大侠: http://itsay.tech
  Jake: https://i.jakeyu.top/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 海
